name: publish

on:
  push:
    branches: [ master ]
    tags: ['**']

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: get git tag
        id: git_info
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "::set-output name=tag::${GITHUB_REF##*/}"
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64,ppc64le
      - uses: docker/setup-buildx-action@v1
        id: buildx
      - name: docker buildx build
        env:
          git_tag: ${{ steps.git_info.outputs.tag }}
        run: |
          dock_image="${GITHUB_REPOSITORY,,}"  # to lower case
          tag="${git_tag:-latest}"  # if build triggered by tag, use tag name
          docker buildx build -t $dock_image:$tag --platform ${{ steps.buildx.outputs.platforms }} --progress plain .
# TODO docker login
